In [1]:
import pennylane as qml
from circuits import *
from main import main

In [11]:
# BS
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

num_pars = 10
par_var = 2
dim_w = 5

rng = np.random.default_rng()
rand_pars_var = rng.choice(dim_w, par_var, replace = False)
fixed_nvec = np.random.uniform(low=-np.pi, high=np.pi, size=dim_w)

nvecs = np.zeros(shape=(num_pars, dim_w))

for i in range(num_pars):
    for j in range(dim_w):
        if j in rand_pars_var:
            nvecs[i][j] = np.random.uniform(low=-np.pi, high=np.pi, size=1)
        else:
            nvecs[i][j] = fixed_nvec[j]
print(rand_pars_var)
print(nvecs)

[3 2]
[[ 1.30327612 -2.44405877 -1.72279433 -2.30056107 -0.05233943]
 [ 1.30327612 -2.44405877  0.54408417  1.01440424 -0.05233943]
 [ 1.30327612 -2.44405877  2.63059138  2.04006416 -0.05233943]
 [ 1.30327612 -2.44405877 -2.89681632  2.29218389 -0.05233943]
 [ 1.30327612 -2.44405877 -0.53040449  2.29774333 -0.05233943]
 [ 1.30327612 -2.44405877 -1.94013212 -3.06586799 -0.05233943]
 [ 1.30327612 -2.44405877 -2.59247154 -0.16193813 -0.05233943]
 [ 1.30327612 -2.44405877 -1.42696813  0.50275474 -0.05233943]
 [ 1.30327612 -2.44405877 -0.62529522  2.74919247 -0.05233943]
 [ 1.30327612 -2.44405877 -0.46708214  2.34359813 -0.05233943]]


In [ ]:
# Experiment 16

for layers_x in range(2,11):
    print(layers_x)

    folder_name = f"16. 1D, Lp=1, increasing Lx and n"
    dim_x = 1
    # layers_x = 2
    layers_p = 1
    n_qubits = layers_x*dim_x
    circuit_class = Circuit_big # Simple_circuit_marked, Circuit_with_weights, Circuit_n, Circuit_1qubit, Circuit_big

    circuit = circuit_class(n_qubits, dim_x, layers_x, layers_p)
    weights_samples = 10000**(1/circuit.dim_w)
    weights_search = "random"  # random, grid
    bins_hist = 100
    num_cpus = 160

    dev = qml.device('lightning.qubit', wires=circuit.n_qubits)
    main(weights_samples, weights_search, bins_hist, circuit, dev, folder_name, num_cpus)

In [4]:
# Experiment 14 and 15

for layers_x in range(2,11):
    print(layers_x)

    folder_name = f"15. 10q, 1D, Lp=1, increasing Lx"
    dim_x = 1
    # layers_x = 2
    layers_p = 1
    n_qubits = 10 #layers_x*dim_x
    circuit_class = Circuit_big # Simple_circuit_marked, Circuit_with_weights, Circuit_n, Circuit_1qubit, Circuit_big

    circuit = circuit_class(n_qubits, dim_x, layers_x, layers_p)
    weights_samples = 10000**(1/circuit.dim_w)
    weights_search = "random"  # random, grid
    bins_hist = 100
    num_cpus = 160

    dev = qml.device('lightning.qubit', wires=circuit.n_qubits)
    main(weights_samples, weights_search, bins_hist, circuit, dev, folder_name, num_cpus)

2
8.299137353897095s - circuit_big - w=10000, x=1, n=10, Lx=2, Lp=1 - 29-06-2023 19-36-39
3
8.24583125114441s - circuit_big - w=10000, x=1, n=10, Lx=3, Lp=1 - 29-06-2023 19-36-48
4
9.219241380691528s - circuit_big - w=10000, x=1, n=10, Lx=4, Lp=1 - 29-06-2023 19-36-59
5
11.329705715179443s - circuit_big - w=10000, x=1, n=10, Lx=5, Lp=1 - 29-06-2023 19-37-11
6
11.172738552093506s - circuit_big - w=10000, x=1, n=10, Lx=6, Lp=1 - 29-06-2023 19-37-23
7
15.268542051315308s - circuit_big - w=10000, x=1, n=10, Lx=7, Lp=1 - 29-06-2023 19-37-39
8
14.356186628341675s - circuit_big - w=10000, x=1, n=10, Lx=8, Lp=1 - 29-06-2023 19-37-55
9
17.32913827896118s - circuit_big - w=10000, x=1, n=10, Lx=9, Lp=1 - 29-06-2023 19-38-13
10
23.248453378677368s - circuit_big - w=10000, x=1, n=10, Lx=10, Lp=1 - 29-06-2023 19-38-37


<Figure size 640x480 with 0 Axes>

In [ ]:
# Experiment 13

for layers_x in range(1,6):
    for layers_p in range(1,11):
        print(layers_p)

        folder_name = f"13. 10q, 2D, Lx={layers_x}, increasing Lp"
        dim_x = 2
        # layers_x = 2
        # layers_p = 1
        n_qubits = 10 #layers_x*dim_x
        circuit_class = Circuit_big # Simple_circuit_marked, Circuit_with_weights, Circuit_n, Circuit_1qubit, Circuit_big
        
        circuit = circuit_class(n_qubits, dim_x, layers_x, layers_p)
        weights_samples = 10000**(1/circuit.dim_w)
        weights_search = "random"  # random, grid
        bins_hist = 100
        num_cpus = 160

        dev = qml.device('lightning.qubit', wires=circuit.n_qubits)
        main(weights_samples, weights_search, bins_hist, circuit, dev, folder_name, num_cpus)

In [ ]:
# Experiment 12

for layers_p in range(1,11):
    print(layers_p)

    folder_name = f"12. 5q, 2D, Lx=2, increasing Lp"
    dim_x = 2
    layers_x = 2
    # layers_p = 1
    n_qubits = 5 #layers_x*dim_x
    circuit_class = Circuit_big # Simple_circuit_marked, Circuit_with_weights, Circuit_n, Circuit_1qubit, Circuit_big
    
    circuit = circuit_class(n_qubits, dim_x, layers_x, layers_p)
    weights_samples = 10000**(1/circuit.dim_w)
    weights_search = "random"  # random, grid
    bins_hist = 100
    num_cpus = 160

    dev = qml.device('lightning.qubit', wires=circuit.n_qubits)
    main(weights_samples, weights_search, bins_hist, circuit, dev, folder_name, num_cpus)

In [ ]:
# Experiment 11

for layers_x in range(1,11):
    print(layers_x)

    folder_name = f"11. 1qubit, 3D, increasing layers"
    dim_x = 3
    # layers_x = 2
    layers_p = 1
    n_qubits = 1 #layers_x*dim_x
    circuit_class = Circuit_1qubit # Simple_circuit_marked, Circuit_with_weights, Circuit_n, Circuit_1qubit, Circuit_big
    
    circuit = circuit_class(n_qubits, dim_x, layers_x, layers_p)
    weights_samples = 10000**(1/circuit.dim_w)
    weights_search = "random"  # random, grid
    bins_hist = 100
    num_cpus = 160

    dev = qml.device('lightning.qubit', wires=circuit.n_qubits)
    main(weights_samples, weights_search, bins_hist, circuit, dev, folder_name, num_cpus)

In [ ]:
# Experiment 10

for layers_x in range(1,11):
    print(layers_x)

    folder_name = f"10. 1qubit, 2D, increasing layers"
    dim_x = 2
    # layers_x = 2
    layers_p = 1
    n_qubits = 1 #layers_x*dim_x
    circuit_class = Circuit_1qubit # Simple_circuit_marked, Circuit_with_weights, Circuit_n, Circuit_1qubit, Circuit_big
    
    circuit = circuit_class(n_qubits, dim_x, layers_x, layers_p)
    weights_samples = 10000**(1/circuit.dim_w)
    weights_search = "random"  # random, grid
    bins_hist = 100
    num_cpus = 160

    dev = qml.device('lightning.qubit', wires=circuit.n_qubits)
    main(weights_samples, weights_search, bins_hist, circuit, dev, folder_name, num_cpus)

In [ ]:
# Experiment 09

for layers_x in range(1,11):
    print(layers_x)

    folder_name = f"09. 1qubit, 1D, increasing layers"
    dim_x = 1
    # layers_x = 2
    layers_p = 1
    n_qubits = 1 #layers_x*dim_x
    circuit_class = Circuit_1qubit # Simple_circuit_marked, Circuit_with_weights, Circuit_n, Circuit_1qubit, Circuit_big
    
    circuit = circuit_class(n_qubits, dim_x, layers_x, layers_p)
    weights_samples = 10000**(1/circuit.dim_w)
    weights_search = "random"  # random, grid
    bins_hist = 100
    num_cpus = 160

    dev = qml.device('lightning.qubit', wires=circuit.n_qubits)
    main(weights_samples, weights_search, bins_hist, circuit, dev, folder_name, num_cpus)

In [ ]:
# Experiment 08

for dim_x in range(1,11):
    print(dim_x)

    folder_name = f"08. Layers = 2, increasing dim_x and n"
    # dim_x = 2
    layers_x = 2
    layers_p = 1
    n_qubits = layers_x*dim_x
    circuit_class = Circuit_3 # Simple_circuit_marked, Circuit_with_weights, Circuit_n, Circuit_1qubit, Circuit_big
    
    circuit = circuit_class(n_qubits, dim_x, layers_x, layers_p)
    weights_samples = 10000**(1/circuit.dim_w)
    weights_search = "random"  # random, grid
    bins_hist = 100
    num_cpus = 160

    dev = qml.device('lightning.qubit', wires=circuit.n_qubits)
    main(weights_samples, weights_search, bins_hist, circuit, dev, folder_name, num_cpus)

In [ ]:
# Experiment 07

for dim_x in range(2,11):
    print(dim_x)

    folder_name = f"07. Layers = 1, increasing dim_x and n"
    # dim_x = 2
    layers_x = 1
    layers_p = 1
    n_qubits = layers_x*dim_x
    circuit_class = Circuit_3 # Simple_circuit_marked, Circuit_with_weights, Circuit_n, Circuit_1qubit, Circuit_big
    
    circuit = circuit_class(n_qubits, dim_x, layers_x, layers_p)
    weights_samples = 10000**(1/circuit.dim_w)
    weights_search = "random"  # random, grid
    bins_hist = 100
    num_cpus = 160

    dev = qml.device('lightning.qubit', wires=circuit.n_qubits)
    main(weights_samples, weights_search, bins_hist, circuit, dev, folder_name, num_cpus)

In [3]:
# Experiment 06

for dim_x in range(1,11):
    print(dim_x)

    folder_name = f"06. Circuit 3, 10qubits, max L, increasing dim_x"
    # dim_x = 2
    n_qubits = 10 #layers_x*dim_x
    layers_x = n_qubits//dim_x
    layers_p = 1
    
    circuit_class = Circuit_3 # Simple_circuit_marked, Circuit_with_weights, Circuit_n, Circuit_1qubit, Circuit_big
    
    circuit = circuit_class(n_qubits, dim_x, layers_x, layers_p)
    weights_samples = 10000**(1/circuit.dim_w)
    weights_search = "random"  # random, grid
    bins_hist = 100
    num_cpus = 160

    dev = qml.device('lightning.qubit', wires=circuit.n_qubits)
    main(weights_samples, weights_search, bins_hist, circuit, dev, folder_name, num_cpus)

1
6.855780363082886s - circuit_3 - w=10000, x=1, n=10, Lx=10, Lp=1 - 28-06-2023 06-39-55
2
30.163984060287476s - circuit_3 - w=10000, x=2, n=10, Lx=5, Lp=1 - 28-06-2023 06-40-26
3
79.53605675697327s - circuit_3 - w=10000, x=3, n=10, Lx=3, Lp=1 - 28-06-2023 06-41-47
4
138.38215279579163s - circuit_3 - w=10000, x=4, n=10, Lx=2, Lp=1 - 28-06-2023 06-44-06
5


Process ForkPoolWorker-779:
Process ForkPoolWorker-738:
Process ForkPoolWorker-782:
Process ForkPoolWorker-758:
Process ForkPoolWorker-767:
Process ForkPoolWorker-740:
Process ForkPoolWorker-749:
Process ForkPoolWorker-780:
Process ForkPoolWorker-776:
Process ForkPoolWorker-797:
Process ForkPoolWorker-765:
Process ForkPoolWorker-732:
Process ForkPoolWorker-751:
Process ForkPoolWorker-675:
Process ForkPoolWorker-670:
Process ForkPoolWorker-685:
Process ForkPoolWorker-684:
Process ForkPoolWorker-665:
Process ForkPoolWorker-644:


KeyboardInterrupt: 

Process ForkPoolWorker-720:
Process ForkPoolWorker-743:
Process ForkPoolWorker-742:


<Figure size 640x480 with 0 Axes>

Process ForkPoolWorker-777:
Process ForkPoolWorker-645:
Process ForkPoolWorker-706:
Process ForkPoolWorker-682:
Process ForkPoolWorker-671:
Process ForkPoolWorker-662:
Process ForkPoolWorker-646:
Process ForkPoolWorker-756:
Process ForkPoolWorker-725:
Process ForkPoolWorker-653:
Process ForkPoolWorker-679:
Process ForkPoolWorker-677:
Process ForkPoolWorker-664:
Process ForkPoolWorker-727:
Process ForkPoolWorker-733:
Process ForkPoolWorker-799:
Process ForkPoolWorker-787:
Process ForkPoolWorker-656:
Process ForkPoolWorker-649:
Process ForkPoolWorker-766:
Process ForkPoolWorker-737:
Process ForkPoolWorker-703:
Process ForkPoolWorker-772:
Process ForkPoolWorker-700:
Process ForkPoolWorker-792:
Process ForkPoolWorker-694:
Process ForkPoolWorker-722:
Process ForkPoolWorker-760:
Process ForkPoolWorker-642:
Process ForkPoolWorker-757:
Process ForkPoolWorker-741:
Process ForkPoolWorker-794:
Process ForkPoolWorker-687:
Process ForkPoolWorker-761:
Process ForkPoolWorker-668:
Process ForkPoolWork

In [ ]:
# Experiment 05

for layers_x in range(1,11):
    print(layers_x)

    folder_name = f"05. Circuit 1, 2L qubits, 2D, increasing L"
    dim_x = 2
    # layers_x = 2
    layers_p = 1
    n_qubits = layers_x*dim_x
    circuit_class = Circuit_1 # Simple_circuit_marked, Circuit_with_weights, Circuit_n, Circuit_1qubit, Circuit_big
    
    circuit = circuit_class(n_qubits, dim_x, layers_x, layers_p)
    weights_samples = 10000**(1/circuit.dim_w)
    weights_search = "random"  # random, grid
    bins_hist = 100
    num_cpus = 160

    dev = qml.device('lightning.qubit', wires=circuit.n_qubits)
    main(weights_samples, weights_search, bins_hist, circuit, dev, folder_name, num_cpus)

In [3]:
# Experiment 04

for layers_x in range(2,11):
    print(layers_x)

    folder_name = f"04. Circuit 3 10qubits 1D increasing L"
    dim_x = 1
    # layers_x = 2
    layers_p = 1
    n_qubits = 10 #layers_x*dim_x
    circuit_class = Circuit_3 # Simple_circuit_marked, Circuit_with_weights, Circuit_n, Circuit_1qubit, Circuit_big
    
    circuit = circuit_class(n_qubits, dim_x, layers_x, layers_p)
    weights_samples = 10000**(1/circuit.dim_w)
    weights_search = "random"  # random, grid
    bins_hist = 100
    num_cpus = 160

    dev = qml.device('lightning.qubit', wires=circuit.n_qubits)
    main(weights_samples, weights_search, bins_hist, circuit, dev, folder_name, num_cpus)

2
2.2875707149505615s - circuit_3 - w=10000, x=1, n=10, Lx=2, Lp=1 - 28-06-2023 06-20-13
3
2.6030538082122803s - circuit_3 - w=10000, x=1, n=10, Lx=3, Lp=1 - 28-06-2023 06-20-16
4
3.222985029220581s - circuit_3 - w=10000, x=1, n=10, Lx=4, Lp=1 - 28-06-2023 06-20-20
5
3.736394166946411s - circuit_3 - w=10000, x=1, n=10, Lx=5, Lp=1 - 28-06-2023 06-20-25
6
4.240832090377808s - circuit_3 - w=10000, x=1, n=10, Lx=6, Lp=1 - 28-06-2023 06-20-30
7
4.823790073394775s - circuit_3 - w=10000, x=1, n=10, Lx=7, Lp=1 - 28-06-2023 06-20-36
8
5.418293237686157s - circuit_3 - w=10000, x=1, n=10, Lx=8, Lp=1 - 28-06-2023 06-20-42
9
6.146125078201294s - circuit_3 - w=10000, x=1, n=10, Lx=9, Lp=1 - 28-06-2023 06-20-49
10
6.637263536453247s - circuit_3 - w=10000, x=1, n=10, Lx=10, Lp=1 - 28-06-2023 06-20-57


<Figure size 640x480 with 0 Axes>

In [ ]:
# Experiment 03

for layers_x in range(2,11):
    print(layers_x)

    folder_name = f"03. Circuit_1 1D 100.000"
    dim_x = 1
    # layers_x = 2
    layers_p = 1
    n_qubits = layers_x*dim_x
    circuit_class = Circuit_1 # Simple_circuit_marked, Circuit_with_weights, Circuit_n, Circuit_1qubit, Circuit_big
    
    circuit = circuit_class(n_qubits, dim_x, layers_x, layers_p)
    weights_samples = 100000**(1/circuit.dim_w)
    weights_search = "random"  # random, grid
    bins_hist = 100
    num_cpus = 160

    dev = qml.device('lightning.qubit', wires=circuit.n_qubits)
    main(weights_samples, weights_search, bins_hist, circuit, dev, folder_name, num_cpus)

In [2]:
# Experiment 02

for layers_x in range(2,11):
    print(layers_x)

    folder_name = f"02. Circuit_2 1D 10.000"
    dim_x = 1
    # layers_x = 2
    layers_p = 1
    n_qubits = layers_x*dim_x
    circuit_class = Circuit_2 # Simple_circuit_marked, Circuit_with_weights, Circuit_n, Circuit_1qubit, Circuit_big
    
    circuit = circuit_class(n_qubits, dim_x, layers_x, layers_p)
    weights_samples = 10000**(1/circuit.dim_w)
    weights_search = "random"  # random, grid
    bins_hist = 100
    num_cpus = 160

    dev = qml.device('lightning.qubit', wires=circuit.n_qubits)
    main(weights_samples, weights_search, bins_hist, circuit, dev, folder_name, num_cpus)

2
1.5133967399597168s - circuit_2 - w=10000, x=1, n=2, Lx=2, Lp=1 - 28-06-2023 06-19-17
3
2.316668748855591s - circuit_2 - w=10000, x=1, n=3, Lx=3, Lp=1 - 28-06-2023 06-19-21
4
3.4076426029205322s - circuit_2 - w=10000, x=1, n=4, Lx=4, Lp=1 - 28-06-2023 06-19-25
5
3.9819536209106445s - circuit_2 - w=10000, x=1, n=5, Lx=5, Lp=1 - 28-06-2023 06-19-30
6
4.685390949249268s - circuit_2 - w=10000, x=1, n=6, Lx=6, Lp=1 - 28-06-2023 06-19-35
7
5.71190071105957s - circuit_2 - w=10000, x=1, n=7, Lx=7, Lp=1 - 28-06-2023 06-19-42
8
6.990312814712524s - circuit_2 - w=10000, x=1, n=8, Lx=8, Lp=1 - 28-06-2023 06-19-50
9
7.960871696472168s - circuit_2 - w=10000, x=1, n=9, Lx=9, Lp=1 - 28-06-2023 06-19-59
10
9.66928744316101s - circuit_2 - w=10000, x=1, n=10, Lx=10, Lp=1 - 28-06-2023 06-20-10


<Figure size 640x480 with 0 Axes>

In [ ]:
# Experiment 01

for layers_x in range(2,11):
    print(layers_x)

    folder_name = f"01. Circuit_1 1D 10.000"
    dim_x = 1
    # layers_x = 2
    layers_p = 1
    n_qubits = layers_x*dim_x
    circuit_class = Circuit_1 # Simple_circuit_marked, Circuit_with_weights, Circuit_n, Circuit_1qubit, Circuit_big
    
    circuit = circuit_class(n_qubits, dim_x, layers_x, layers_p)
    weights_samples = 10000**(1/circuit.dim_w)
    weights_search = "random"  # random, grid
    bins_hist = 100
    num_cpus = 160

    dev = qml.device('lightning.qubit', wires=circuit.n_qubits)
    main(weights_samples, weights_search, bins_hist, circuit, dev, folder_name, num_cpus)